system_roles: ["普通用户","编辑","管理员"]
categoies: ["前瞻","评测","业界评论"]
topics: ["首页","游戏",'搜索']
platforms: [ "PC","XBOX360", "XBOXONE", "PS3", "PS4", "PSV", "WiiU" ,"3DS", "PSP", "NDS", "Wii"]
sale_units: ['美元','元','港币','日元','韩元','欧元','马克','卢布','镑','法郎','盾','克朗']