# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 933dc3e8b48a8cdc607aa823fdbeb26c687e920bde5750f6360ad32aea4139d0800752056268cd4f1091af0c6c0ce02c296ebc5120cfab081eb707c9b6ce4b41

test:
  secret_key_base: 1eec04406e3d7cd9da55b53b0e2ce31428786b07ea4ce268b510c11968492c73b07bbe6275f5715e58adedf482d2e82551b39e55a16bc788e03b98be57c833af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
